punters:
  - name: greedy-irori-0806-1706
    shell: prebuilts/punter-0806-1706 --logtostderr --punter=GreedyPunter --name=GreedyPunter
  - name: greedy-chun-0806-1706
    shell: prebuilts/punter-0806-1706 --logtostderr --punter=GreedyPunterChun --name=GreedyPunterChun
  - name: greedy-mirac-0806-1706
    shell: prebuilts/punter-0806-1706 --logtostderr --punter=GreedyPunterMirac --name=GreedyPunterMirac
  - name: greedy-jam-0806-1706
    shell: prebuilts/punter-0806-1706 --logtostderr --punter=GreedyToJam --name=GreedyToJam
