punters:
  - name: lightning
    shell: prebuilts/punter-0806-1327 --logtostderr --name=lightning --punter=GreedyPunter
  - name: greedy-chun
    shell: prebuilts/punter-0806-1327 --logtostderr --name=greedy-chun --punter=GreedyPunterChun
