configurations:
  - name: sample.2p
    map: sample
    num_punters: 2
    num_games: 2
  - name: boston-sparse.2p
    map: boston-sparse
    num_punters: 2
    num_games: 1
  - name: circle.2p
    map: circle
    num_punters: 2
    num_games: 1
  - name: edinburgh-scaled.2p
    map: edinburgh-scaled
    num_punters: 2
    num_games: 1
  - name: edinburgh-sparse2.2p
    map: edinburgh-sparse2
    num_punters: 2
    num_games: 1
  - name: edinburgh-sparse.2p
    map: edinburgh-sparse
    num_punters: 2
    num_games: 1
  - name: gen1.2p
    map: gen1
    num_punters: 2
    num_games: 1
  - name: gen2.2p
    map: gen2
    num_punters: 2
    num_games: 1
  - name: gen3.2p
    map: gen3
    num_punters: 2
    num_games: 1
  - name: gen4.2p
    map: gen4
    num_punters: 2
    num_games: 1
  - name: gothenburg-sparse.2p
    map: gothenburg-sparse
    num_punters: 2
    num_games: 1
  - name: lambda.2p
    map: lambda
    num_punters: 2
    num_games: 1
  - name: nara-scaled.2p
    map: nara-scaled
    num_punters: 2
    num_games: 1
  - name: nara-sparse.2p
    map: nara-sparse
    num_punters: 2
    num_games: 1
  - name: oxford2-scaled.2p
    map: oxford2-scaled
    num_punters: 2
    num_games: 1
  - name: oxford2-sparse-2.2p
    map: oxford2-sparse-2
    num_punters: 2
    num_games: 1
  - name: oxford2-sparse.2p
    map: oxford2-sparse
    num_punters: 2
    num_games: 1
  - name: oxford-3000-nodes.2p
    map: oxford-3000-nodes
    num_punters: 2
    num_games: 1
  - name: oxford-center-sparse.2p
    map: oxford-center-sparse
    num_punters: 2
    num_games: 1
  - name: oxford-sparse2.2p
    map: oxford-sparse2
    num_punters: 2
    num_games: 1
  - name: oxford-sparse.2p
    map: oxford-sparse
    num_punters: 2
    num_games: 1
  - name: randomMedium.2p
    map: randomMedium
    num_punters: 2
    num_games: 1
  - name: randomSparse.2p
    map: randomSparse
    num_punters: 2
    num_games: 1
  - name: Sierpinski-triangle.2p
    map: Sierpinski-triangle
    num_punters: 2
    num_games: 1
  - name: spider_web.2p
    map: spider_web
    num_punters: 2
    num_games: 1
  - name: t1.2p
    map: t1
    num_punters: 2
    num_games: 1
  - name: tube.2p
    map: tube
    num_punters: 2
    num_games: 1
  - name: van-city-sparse.2p
    map: van-city-sparse
    num_punters: 2
    num_games: 1


punters:
  - name: lightning
    shell: prebuilts/v3 --logtostderr --name=lightning --punter=GreedyPunter
  - name: greedy-chun-v3
    shell: prebuilts/v3 --logtostderr --name=greedy-chun-v3 --punter=GreedyPunterChun
#  - name: random-v3
#    shell: prebuilts/v3 --logtostderr --name=random-v3 --punter=RandomPunter
#  - name: pass
#    shell: punter/pass-py/pass.py --bot=pass
