cc_library(
  name = "random_punter",
  srcs = [
    "random_punter.cc",
  ],
  hdrs = [
    "random_punter.h",
  ],

  deps = [
    "//third_party/chromiumbase",
    "//framework:simple_punter",
  ],
  visibility = ["//visibility:public"]
)
