#!/bin/bash

cd "$(dirname "$0")"

exec prebuilts/punter-0807-1924 \
  --logtostderr \
  --name=GennAI \
  --punter=MetaPunter \
  --primary_worker_options="--logtostderr --name=mjf --punter=MiracOrJamOrFriendly" \
  --backup_worker_options="--logtostderr --name=quick --punter=QuickPunter" \
  "$@"
